// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A smart upselling AI agent.
 *
 * - smartUpselling - A function that handles the smart upselling process.
 * - SmartUpsellingInput - The input type for the smartUpselling function.
 * - SmartUpsellingOutput - The return type for the smartUpselling function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SmartUpsellingInputSchema = z.object({
  currentOrder: z.string().describe('The current order of the customer.'),
});
export type SmartUpsellingInput = z.infer<typeof SmartUpsellingInputSchema>;

const SmartUpsellingOutputSchema = z.object({
  upsellSuggestions: z
    .array(z.string())
    .describe('An array of upsell suggestions based on the current order.'),
});
export type SmartUpsellingOutput = z.infer<typeof SmartUpsellingOutputSchema>;

export async function smartUpselling(input: SmartUpsellingInput): Promise<SmartUpsellingOutput> {
  return smartUpsellingFlow(input);
}

const prompt = ai.definePrompt({
  name: 'smartUpsellingPrompt',
  input: {schema: SmartUpsellingInputSchema},
  output: {schema: SmartUpsellingOutputSchema},
  prompt: `You are a smart upselling AI agent for a restaurant.

  Based on the customer's current order, suggest relevant upsells and add-ons to increase the average order value and improve the dining experience.

  Current Order: {{{currentOrder}}}

  Suggest some upsells.`,
});

const smartUpsellingFlow = ai.defineFlow(
  {
    name: 'smartUpsellingFlow',
    inputSchema: SmartUpsellingInputSchema,
    outputSchema: SmartUpsellingOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
