-- AlterTable
ALTER TABLE "MenuCategory" ADD COLUMN     "defaultPrinterRole" "PrinterRole";

-- AlterTable
ALTER TABLE "MenuItem" ALTER COLUMN "price" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "Modifier" ALTER COLUMN "priceChange" SET DEFAULT 0,
ALTER COLUMN "priceChange" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "Order" ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "taxRate" SET DEFAULT 0,
ALTER COLUMN "taxRate" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "taxAmount" SET DEFAULT 0,
ALTER COLUMN "taxAmount" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "totalAmount" SET DEFAULT 0,
ALTER COLUMN "totalAmount" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "OrderItem" ALTER COLUMN "unitPrice" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "totalPrice" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "selectedModifiers" DROP NOT NULL;
